# Generated by Django 3.0.7 on 2020-06-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=9999, null=True, verbose_name='№ в последовательности статей (необязательно)')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('annotation', models.CharField(max_length=200, verbose_name='Аннотация')),
                ('preview', models.ImageField(blank=True, default='/static/img/def_post_img.jpg', upload_to='main/paragraph_img/img', verbose_name='Превью')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('color', models.CharField(max_length=7, verbose_name='Цвет (000000)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='/static/img/def_ava.jpg', upload_to='main/user_data/photo', verbose_name='Фото (квадратное)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=9999, null=True, verbose_name='№ в последовательности параграфов статьи (необязательно)')),
                ('class_list', models.CharField(blank=True, max_length=100, null=True, verbose_name='classList')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_paragraph', to='main.Post')),
            ],
            options={
                'verbose_name': 'Параграф статьи',
                'verbose_name_plural': 'Параграфы статьи',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='post', to='main.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=None, null=True, verbose_name='№ в последовательности элементов параграфа (необязательно)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Длинный текст')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткий текст')),
                ('element_type', models.CharField(choices=[('p', 'p'), ('h2', 'h2')], default='p', max_length=30)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='main.PostParagraph')),
            ],
            options={
                'verbose_name': 'Элемент параграфа',
                'verbose_name_plural': 'Элементы параграфа',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Текст')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
