# Generated by Django 3.0.7 on 2020-06-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
