# Generated by Django 3.0.7 on 2020-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200612_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='colr',
            field=models.CharField(default=1, max_length=10, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
