# Generated by Django 3.0.7 on 2020-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Прошла проверку'),
        ),
    ]
