# Generated by Django 3.0.7 on 2020-06-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Технологии', 'Технологии'), ('Путешествия', 'Путешествия'), ('Разное', 'Разное')], default='Разное', max_length=30, verbose_name='Категория'),
        ),
    ]
