# Generated by Django 3.0.7 on 2020-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200613_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='annotation',
            field=models.CharField(default=' ', max_length=200, verbose_name='Кратко о Вас'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Вы можете писать в виде html-разметки или просто текст', verbose_name='Текст статьи'),
        ),
    ]
