# Generated by Django 3.0.7 on 2020-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.CharField(blank=True, default='#', help_text='Необязательное поле. Ненумерованные статьи располагаются после нумерованых в порядке их создания', max_length=4, null=True, verbose_name='№ в последовательности статей'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, default='main/user_data/photo/def_ava.jpg', help_text='Портретная ориентация, лучше квадратное изображение', upload_to='main/user_data/photo', verbose_name='Фото'),
        ),
    ]
